
spring:
  datasource:
    password: letmein
    url: jdbc:mysql://localhost:3306/moviedb
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true